### ISSUE TITLE
Interactive tendril plot marker size should adapt to data.

### ISSUE THREAD

**Issue by Karpefors** [Karpefors/Tendril#1]
I would like to create an interactive plot using the plotly package.
I have noticed that there is a problem with the size of the markers. In some cases, the marker size shift in the middle of a tendril, which should not be the case.

**Comment by stefanoborini** [comment]
At a quick glance, unless we already have some code on this, it is a task that will take some time.
I need to get competent with a fair number of technologies I am not familiar with. I'd keep it for last.

**Comment by stefanoborini** [comment]
Ok, I found the plot.interactive routine. I suspect this will need plotly as a dep so I am adding it.

**Comment by stefanoborini** [comment]
Ref pull request #9

**Comment by stefanoborini** [comment]
@Karpefors I see the problem of the markers being currently too small. A TermsCount/10, rather than 100, gives a nicer result. Do you have a screenshot of the marker size shift issue itself? It might be a bug of plotly or your browser (unlikely, but worth checking)

**Comment by Karpefors** [comment]
This number should not be hard coded. It will be dependent on the size of the study. When I set it to 100 I used a very large study. Thus the numeric factor should be based on max TermsCount and adjusted to a reasonable value.
