### ISSUE TITLE
Time series of net event

### ISSUE THREAD

**Issue by Karpefors** [Karpefors/Tendril#3]
Function to plot time series of net events on active arm for a selected tendril(s).

**Comment by stefanoborini** [comment]
I need more information for this. I am not a statistician.

**Comment by mark-edmondson-jones** [comment]
I understand that this is Martin's ae.time.series function.

**Comment by Karpefors** [comment]
Correct. This is the ae.time.series function available in the word document. However, I can see that I hard coded the treatments in that version. The treatment arms should come from the treat variable in the tendril object passed to the function. 
In addition, it would be useful to pass more than one term to the function. I can have a look at that.

**Comment by stefanoborini** [comment]
Is this what you expect from the plot for AE33?

![Screenshot 2019-10-08 at 13 31 21](https://user-images.githubusercontent.com/132967/66395671-efab6500-e9cf-11e9-9c01-a3abc5be6547.png)

**Comment by stefanoborini** [comment]
Would you see this result to be obtained via an invocation of timeseries(tendril, term) or via plot(tendril, someoption, term) ?

**Comment by Karpefors** [comment]
Yes, it looks as it should.
Being a completely different kind of plot I would argue for having it as a separate function call along the lines of: timeseries(tendril, term). It is not implemented in the current function, but it would be useful to be able to select more than one term.

**Comment by mark-edmondson-jones** [comment]
I've made some changes to a) pick up actual treatments; b) remove warning on dcast; c) change ggplot cosmetics (and y axis label)

**Comment by mark-edmondson-jones** [comment]
I was going to look at the enhancement to plot >1 term next, if required.

**Comment by stefanoborini** [comment]
@mark-edmondson-jones I am already working on this.

**Comment by mark-edmondson-jones** [comment]
We seem to have some overlap.  I have been working on allowing ae_timeseries to take multiple terms.  This now seems to be working, although there is some confusion over the naming.  Should this be ae.time.series?  Or ae.time.series?
Martin - does this look like what you had in mind?
![image](https://user-images.githubusercontent.com/55883203/66414272-fa2a2680-e9f0-11e9-8b14-4404c0026ed4.png)

**Comment by Karpefors** [comment]
This was exactly what I had in mind. It looks like all three of us has decided to work on this simultaneously. Therefore, there might be some confusion. However, Stefano has made a good start and if we can merge your chanes to his branch we should be in a good position.

**Comment by mark-edmondson-jones** [comment]
Yes - there does seem to have been some confusion, but presumably the different changes can be merged.  I have made some further changes to ae_timeseries.  It not allows the argument term to be either a) NULL; b) a single character string; or c) a vector of character strings.  For a) it produces a plot with all AEs, for b) it produces a plot with a single AE (and a title), and for c) or produces a plot with the chosen AEs (and a legend).  See the following examples...
![image](https://user-images.githubusercontent.com/55883203/66459809-a01b7680-ea6d-11e9-87fe-4b0cd072454f.png)
![image](https://user-images.githubusercontent.com/55883203/66459847-af9abf80-ea6d-11e9-9ee2-f2b57577f4fc.png)
![image](https://user-images.githubusercontent.com/55883203/66459874-be817200-ea6d-11e9-9e63-7b6b6347bc1f.png)
Hope this is OK.

**Comment by mark-edmondson-jones** [comment]
[ae_timeseries.zip](https://github.com/Karpefors/Tendril/files/3713306/ae_timeseries.zip)

**Comment by stefanoborini** [comment]
Closed by #57
