### ISSUE TITLE
Permutation analysis plot

### ISSUE THREAD

**Issue by Karpefors** [Karpefors/Tendril#4]
Introduce a new and nicer way to plot the permutation plot. Each simulated tendril should be in light grey; the percentiles should be in dark grey; and the actual tendril should be according to the selected coloring method (e.g. the p-value-adjusted coloring).

**Comment by stefanoborini** [comment]
This should be simple once I learn ggplot (I have no experience with it, but seems straightforward to use, albeit with a large palette of options)

**Comment by stefanoborini** [comment]
@Karpefors I am unable to plot any other plot type other than basic due to the already reported error in #39

**Comment by mark-edmondson-jones** [comment]
I shouldbe able to make the ggplot changes, as I am familiar with ggplot2.

**Comment by mark-edmondson-jones** [comment]
@Karpefors : I cannot get plot.permut.simple.R to work, as it calls TendrilPi without required arguments, in particular term.  Given that significant changes have been made to the permutation and percentile plots would it be enough to make the colour changes to these functions and drop plot.permut.simple.R?  Or is there additional functionality that it introduces?

**Comment by Karpefors** [comment]
No, no new functionality. If we can just redesign according to the new function, it is no problem using the old function.

**Comment by mark-edmondson-jones** [comment]
That sounds easier.  I will look at it later today.
