### ISSUE TITLE
Replace current permutation/percentile function with perm.permut.perc.simple

### ISSUE THREAD

**Issue by stefanoborini** [Karpefors/Tendril#45]
The current perm.permut.perc.simple file contains a routine that is supposed to replace the current code from plotpercentile/plotpermutation.

**Comment by stefanoborini** [comment]
@Karpefors what is the current state of the plot.permut.perc.simple routine? It does not seem to work as a drop in replacement.

It also looks like tendril.pi is replaced on the TendrilPerm object. Is this expected, or should it work with the TendrilPi calculated in the constructor for TendrilPerm?

**Comment by stefanoborini** [comment]
Conversation has been going on via email.

**Comment by stefanoborini** [comment]
Ok, I'll finalize this tomorrow. Right now I have a jumbled mess in PR #48

**Comment by mark-edmondson-jones** [comment]
Can we add ggplot2::theme_bw() to both plots for consistency?

**Comment by Karpefors** [comment]
Yes, let's go with BW theme.

**Comment by stefanoborini** [comment]
@mark-edmondson-jones leaving this to you. I start creating the basic for the package.

**Comment by mark-edmondson-jones** [comment]
Completed.  The new percentfile function (plot.permut.perc.simple)  is not invoked though, is it?

**Comment by stefanoborini** [comment]
> Completed

Have you opened the PR?

> The new percentfile function (plot.permut.perc.simple) is not invoked though, is it?

It is not. Can you please do that as well? I am in the middle of something with maic.

**Comment by mark-edmondson-jones** [comment]
I have made the change in a branch, commited it and pushed it back.  Not sure if that this the same as a PR, or not?  (I am not a Git expert.)

I will look at plot.permut.perc.simple when I have chance.  I am working on something else too today.

**Comment by stefanoborini** [comment]
it is not, you have to open a PR for the specific branch https://github.com/Karpefors/Tendril/branches

**Comment by stefanoborini** [comment]
@mark-edmondson-jones

**Comment by mark-edmondson-jones** [comment]
See #4 regarding plot.permut.perc.simple
