### ISSUE TITLE
Argument passing to plot.TendrilPerm

### ISSUE THREAD

**Issue by mark-edmondson-jones** [Karpefors/Tendril#49]
Currently plot.TendrilPerm is defined using

plot.TendrilPerm <- function(x, ...) {
  params <- as.list(substitute(list(...)))

  if (is.null(params$percentile)) {
    params$percentile = FALSE
  }

However … is ignored unless percentile is passed as an optional parameter.  If any other value is returned then no error/warning is given.  Why is the function not declared as 

plot.TendrilPerm <- function(x, percentile=FALSE)

thereby avoiding the need for logic to check for the argument, giving an error if an unnecessary argument is passed, and allowing partial argument matching (useful with a long name like percentile)

**Comment by stefanoborini** [comment]
```
However … is ignored unless percentile is passed as an optional parameter. If any other value is returned then no error/warning is given. Why is the function not declared as

plot.TendrilPerm <- function(x, percentile=FALSE)
```

Because it's an S3 generic function and you get a warning if you don't respect the signature of the generic plot().

```
allowing partial argument matching (useful with a long name like percentile)
```

that is a practice that should be avoided altogether.

**Comment by stefanoborini** [comment]
Specifically:
```
  checking S3 generic/method consistency (394ms)
   plot:
     function(x, ...)
   plot.Tendril:
     function(x, coloring, interactive)
   
   See section ‘Generic functions and methods’ in the ‘Writing R
   Extensions’ manual.

```

Although it seems to me that the main point is the lack of ..., not the presence of specific keywords.

**Comment by stefanoborini** [comment]
It is however worth of additional investigation. What I made there was a quick workaround.

**Comment by mark-edmondson-jones** [comment]
plot.TendrilPerm <- function(x, percentile=FALSE) {

  if (percentile){
    p <- plotpercentile(x)
  } else {
    p <- plotpermutation(x)
  }
  return(p)
}

seems to work fine.  It accepts percent as well as percentile, and gives an error if you give a argument that it doesn't understand (e.g. xlab).

Regarding generic functions, it is not based on the generic plot function.  Rather it uses ggplot2, which is totally different.

Also, I know that a lot of users take advantage of partial argument matching, and especially with long argument names (e.g. percentile) this is useful.  I guess it's just something R users are used to, whether it's generally good practice or not.

**Comment by stefanoborini** [comment]
It is using S3 resolution to dispatch according to the passed object class name.

**Comment by stefanoborini** [comment]
Encouraing users to use partial argument matching creates problems in searching for occurrences and potential mistakes in matching against the proper name. It should be actively discouraged. [See here for details](https://stackoverflow.com/questions/15264994/prevent-partial-argument-matching)

**Comment by mark-edmondson-jones** [comment]
Wasn't encouraging - just recognising that this is how R is used.
