### ISSUE TITLE
Cyclic dependency trying to build the vignettes

### ISSUE THREAD

**Issue by Karpefors** [Karpefors/Tendril#68]

**Comment by stefanoborini** [comment]
Thanks

**Comment by stefanoborini** [comment]
Strangely enough I can't reproduce it on my setup, so this needs more investigation. In the meantime I fix the various unrelated check failures.

**Comment by Karpefors** [comment]
Strange problem. Let me know if you need a new session with me.
/Martin

Skickat från min iPhone

28 nov. 2019 kl. 10:59 skrev Stefano Borini <notifications@github.com>:

﻿

Strangely enough I can't reproduce it on my setup, so this needs more investigation. In the meantime I fix the various unrelated check failures.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://clicktime.symantec.com/3NumCmS63ukzQBa5ckp5Bn76H2?u=https%3A%2F%2Fgithub.com%2FKarpefors%2FTendril%2Fissues%2F68%3Femail_source%3Dnotifications%26email_token%3DAIBY6EPXOIPH4VML4EDHGF3QV6I6ZA5CNFSM4JQP4CC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFMCOUA%23issuecomment-559425360>, or unsubscribe<https://clicktime.symantec.com/3S3dz6NyyCU38jqqVUFi8XN6H2?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIBY6EIVDNTXXLEUROLO6TLQV6I6ZANCNFSM4JQP4CCQ>.

________________________________

Confidentiality Notice: This message is private and may contain confidential and proprietary information. If you have received this message in error, please notify us and remove it from your system and note that you must not copy, distribute or take any action in reliance on it. Any unauthorized use or disclosure of the contents of this message is not permitted and may be unlawful.

**Comment by stefanoborini** [comment]
This error may be not what it looks like

https://gist.github.com/anonymous/10018579

In other words, R is giving an error message, but we should not trust what it says to find the source of the problem.

**Comment by stefanoborini** [comment]
This problem kind of solved itself. We never found out the reason
