### ISSUE TITLE
Interactive plot color palette

### ISSUE THREAD

**Issue by Karpefors** [Karpefors/Tendril#73]
The color palette used for the interactive plot should look more like the palette used for the basic plot with p.adj coloring type.
It should also have the same limits between 0 and -3 on the log scale.

**Comment by stefanoborini** [comment]
I currently have the following result

![Screenshot 2020-01-10 at 15 30 46](https://user-images.githubusercontent.com/132967/72164751-30938b00-33be-11ea-8f0e-bde669e93eab.png)

please note:

1. I had to change the opacity from a default 0.5 to 1.0. This brings me to the need for an opacity specification. Should we remove it altogether?
2. it seems that it's not possible to color the lines, at least with a simple approach. @mark-edmondson-jones  may know some tricks I am not aware of.

**Comment by Karpefors** [comment]
Hi,
I think it looks good! Not really necessary to have opacity – let’s remove it.
Remember that I struggled with coloring the lines as well and ended up coloring them grey. I think that works. Let’s go with that.
Thanks,
Martin
